# Generated by Django 5.0.6 on 2026-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('priority', models.IntegerField(default=50, help_text='数值越大优先级越高', verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sources', models.CharField(blank=True, default='', help_text='逗号分隔，精确匹配。如 alipay,bocom_debit', max_length=200, verbose_name='来源')),
                ('trans_types', models.CharField(blank=True, default='', help_text='逗号分隔，子串匹配', max_length=200, verbose_name='交易类型')),
                ('directions', models.CharField(blank=True, default='', help_text='逗号分隔：expense / income', max_length=50, verbose_name='收支方向')),
                ('categories', models.CharField(blank=True, default='', help_text='逗号分隔，子串匹配分类名', max_length=200, verbose_name='分类')),
                ('payment_channels', models.CharField(blank=True, default='', help_text='逗号分隔，子串匹配', max_length=200, verbose_name='支付渠道')),
                ('keywords', models.TextField(blank=True, default='', help_text='逗号分隔。搜索范围：description+merchant+counterparty+trans_type+payment_channel', verbose_name='关键词')),
                ('keyword_exclude', models.TextField(blank=True, default='', help_text='逗号分隔。搜索范围同上但不含 payment_channel', verbose_name='排除关键词')),
                ('merchants', models.TextField(blank=True, default='', help_text='逗号分隔，子串匹配', verbose_name='商户')),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最小金额')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最大金额')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('counterparties', models.TextField(blank=True, default='', help_text='逗号分隔，精确匹配 counterparty 字段', verbose_name='对手方')),
            ],
            options={
                'verbose_name': '无效规则',
                'verbose_name_plural': '无效规则',
            },
        ),
        migrations.CreateModel(
            name='ValidRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('priority', models.IntegerField(default=50, help_text='数值越大优先级越高', verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sources', models.CharField(blank=True, default='', help_text='逗号分隔，精确匹配。如 alipay,bocom_debit', max_length=200, verbose_name='来源')),
                ('trans_types', models.CharField(blank=True, default='', help_text='逗号分隔，子串匹配', max_length=200, verbose_name='交易类型')),
                ('directions', models.CharField(blank=True, default='', help_text='逗号分隔：expense / income', max_length=50, verbose_name='收支方向')),
                ('categories', models.CharField(blank=True, default='', help_text='逗号分隔，子串匹配分类名', max_length=200, verbose_name='分类')),
                ('payment_channels', models.CharField(blank=True, default='', help_text='逗号分隔，子串匹配', max_length=200, verbose_name='支付渠道')),
                ('keywords', models.TextField(blank=True, default='', help_text='逗号分隔。搜索范围：description+merchant+counterparty+trans_type+payment_channel', verbose_name='关键词')),
                ('keyword_exclude', models.TextField(blank=True, default='', help_text='逗号分隔。搜索范围同上但不含 payment_channel', verbose_name='排除关键词')),
                ('merchants', models.TextField(blank=True, default='', help_text='逗号分隔，子串匹配', verbose_name='商户')),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最小金额')),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最大金额')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '有效规则',
                'verbose_name_plural': '有效规则',
            },
        ),
    ]
