# Generated by Django 5.0.6 on 2026-06-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('rules', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(verbose_name='交易日期')),
                ('amount', models.DecimalField(decimal_places=2, help_text='绝对值，方向由 direction 决定', max_digits=12, verbose_name='金额')),
                ('direction', models.CharField(choices=[('expense', '支出'), ('income', '收入')], max_length=10, verbose_name='收支方向')),
                ('source', models.CharField(choices=[('alipay', '支付宝'), ('jd', '京东'), ('meituan', '美团'), ('wechat', '微信支付'), ('bocom_debit', '交通银行储蓄卡'), ('cmb_debit', '招商银行储蓄卡'), ('cib_credit', '中信信用卡'), ('cmb_credit', '招商银行信用卡'), ('douyin', '抖音月付')], max_length=20, verbose_name='数据来源')),
                ('status', models.CharField(choices=[('confirmed', '有效'), ('excluded', '无效'), ('unknown', '未知'), ('deleted', '已删除')], default='unknown', max_length=10, verbose_name='状态')),
                ('trans_type', models.CharField(blank=True, default='', max_length=100, verbose_name='交易类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='交易描述')),
                ('merchant', models.CharField(blank=True, default='', max_length=200, verbose_name='商户名')),
                ('counterparty', models.CharField(blank=True, default='', max_length=200, verbose_name='对手方')),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, verbose_name='支付方式')),
                ('payment_channel', models.CharField(blank=True, default='', max_length=100, verbose_name='支付渠道')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_virtual', models.BooleanField(default=False, help_text='结算关闭时生成的净支出虚拟交易', verbose_name='虚拟交易')),
                ('unique_key', models.CharField(help_text='MD5 前 16 位，用于导入去重', max_length=32, unique=True, verbose_name='唯一键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='账户')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='分类')),
                ('invalid_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.invalidrule', verbose_name='命中的无效规则')),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlements.transactionpair', verbose_name='退款配对')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlements.settlementgroup', verbose_name='所属结算组')),
                ('valid_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.validrule', verbose_name='命中的有效规则')),
            ],
            options={
                'verbose_name': '交易',
                'verbose_name_plural': '交易',
                'ordering': ['-trans_date', '-id'],
                'indexes': [models.Index(fields=['trans_date'], name='transaction_trans_d_de406d_idx'), models.Index(fields=['source'], name='transaction_source_36f39f_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['direction'], name='transaction_directi_b7e74f_idx'), models.Index(fields=['unique_key'], name='transaction_unique__a90a09_idx')],
            },
        ),
    ]
