# Generated by Django 5.0.6 on 2026-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='账户名称')),
                ('account_type', models.CharField(choices=[('debit', '储蓄卡'), ('credit', '信用卡'), ('platform', '支付平台')], default='platform', max_length=10, verbose_name='账户类型')),
                ('bank_name', models.CharField(blank=True, default='', max_length=50, verbose_name='银行名称')),
                ('owner', models.CharField(blank=True, default='', max_length=50, verbose_name='持有人')),
                ('match_keywords', models.CharField(blank=True, default='', help_text='逗号分隔，用于导入时自动匹配账户', max_length=200, verbose_name='匹配关键词')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'ordering': ['id'],
            },
        ),
    ]
