# Generated by Django 5.0.6 on 2026-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='结算组名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已结算')], default='open', max_length=10, verbose_name='状态')),
                ('total_advance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='垫付总额')),
                ('total_reimbursement', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='收款总额')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='垫付 - 收款，最低 0', max_digits=12, verbose_name='净支出')),
                ('is_aa', models.BooleanField(default=False, verbose_name='AA群收款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '结算组',
                'verbose_name_plural': '结算组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('advance', '垫付'), ('reimbursement', '收款')], max_length=15, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '结算明细',
                'verbose_name_plural': '结算明细',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0, help_text='0-100，≥60 自动配对', verbose_name='匹配得分')),
                ('match_method', models.CharField(choices=[('auto', '自动配对'), ('manual', '手动配对'), ('aa', 'AA群收款')], default='auto', max_length=10, verbose_name='配对方式')),
                ('match_detail', models.JSONField(blank=True, default=dict, help_text='各维度得分明细', verbose_name='匹配详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '退款配对',
                'verbose_name_plural': '退款配对',
                'ordering': ['-created_at'],
            },
        ),
    ]
