# Generated by Django 5.0.6 on 2026-06-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementgroup',
            name='virtual_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_settlements', to='transactions.transaction', verbose_name='虚拟交易'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlements.settlementgroup', verbose_name='结算组'),
        ),
        migrations.AddField(
            model_name='settlementitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='transactions.transaction', verbose_name='交易'),
        ),
        migrations.AddField(
            model_name='transactionpair',
            name='expense_tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_pairs', to='transactions.transaction', verbose_name='消费交易'),
        ),
        migrations.AddField(
            model_name='transactionpair',
            name='refund_tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_pairs', to='transactions.transaction', verbose_name='退款交易'),
        ),
        migrations.AlterUniqueTogether(
            name='settlementitem',
            unique_together={('settlement', 'transaction')},
        ),
    ]
