# Generated by Django 5.0.6 on 2026-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20, verbose_name='数据来源')),
                ('source_file', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('imported_rows', models.IntegerField(default=0, verbose_name='导入行数')),
                ('skipped_rows', models.IntegerField(default=0, verbose_name='跳过行数')),
                ('error_rows', models.IntegerField(default=0, verbose_name='错误行数')),
                ('error_detail', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '导入日志',
                'verbose_name_plural': '导入日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
